openapi: 3.0.0
info:
  title: API Recomendación de Alimentos
  version: 1.0.0
  description: Registro y login de estudiantes

paths:
  /api/auth/register:
    post:
      summary: Registro de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                middle_name:
                  type: string
                document_number:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuario registrado
        '400':
          description: Error en datos
  /api/auth/login:
    post:
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                document_number:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login exitoso
        '400':
          description: Credenciales incorrectas
